from klassfizyk import wszst
# from random import randint
# ahfioufga = wszst(randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081),randint(1,4780174081))




print('Co obliczasz \n 1 - prędkość \n 2 - drogę \n 3 - czas \n 4 - przyśpieszenie \n 5 - prędkość średnią \n 6 - wykres położenia od czasu \n 7 - przyśpieszenie średnie \n 8 - zmianę prędkości \n 9 - zmianę czasu \n 10 - deltę \n 11 - siłę tarcia \n 12 - siłę grawitacji \n 13 - opór areodynamiczny \n 14 - energię w spoczynku  \n 15 - ciśnienie \n 16 - energię kinetyczną  \n 17 - gęstość \n 18 - siła wyporu')

inp = int(input())

if inp == 1:
    ahfioufga= wszst(float(input('jakie s? ')),
    float(0),
    float(input('jakie t? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujv()
if inp == 2:
    ahfioufga= wszst(float(0),
    float(input('jakie v? ')),
    float(input('jakie t? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujs()
if inp == 3:
    ahfioufga= wszst(float(input('jakie s? ')),
    float(input('jakie v? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujt()
if inp == 4:
    ahfioufga= wszst(float(0),
    float(0),
    float(input('jakie t? ')),
    float(input('jakie v0? ')),
    float(input('jakie vk? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkuluja()
if inp == 5:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(input('jakie v0? ')),
    float(input('jakie vk? ')),
    float(0),
    float(input('jakie t0? ')),
    float(0),
    float(input('jakie tk? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujvsr()
if inp == 6:
    ahfioufga= wszst(float(0),
    float(input('jakie v? ')),
    float(input('jakie t? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie x0? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujxt()
if inp == 7:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(input('jakie v0? ')),
    float(input('jakie vk? ')),
    float(0),
    float(input('jakie t0? ')),
    float(0),
    float(input('jakie tk? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujasr()
if inp == 8:
    ahfioufga= wszst(float(0),
    float(input('jakie v? ')),
    float(0),
    float(input('jakie v0? ')),
    float(input('jakie vk? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujdeltav()
if inp == 9:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie t0? ')),
    float(0),
    float(input('jakie tk? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujdeltat()
if inp == 10:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie a do delty? ')),
    float(input('jakie b do delty? ')),
    float(input('jakie c do delty? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujdelte()
if inp == 11:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie fn? ')),
    float(input('jaki współczynnik tarcia? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujft()
if inp == 12:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie m? ')),
    float(input('jakie g? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujfg()
if inp == 13:
    ahfioufga= wszst(float(0),
    float(input('jakie v? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jaka gęstość powietrza? ')),
    float(input('jaki drag coefficient? ')),
    float(input('jaka powierzchnia? ')),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujopor()
if inp == 14:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie m? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(299792458**2),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujajnstajn()
if inp == 15:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie fn? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jaka powierzchnia? ')),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujprawopascala()
if inp == 16:
    ahfioufga= wszst(float(0),
    float(input('jakie v? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie m? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujpewpew()
if inp == 17:
    ahfioufga= wszst(float(0),
    float(input('jakie v? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie m? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jaka objętość? ')),
    float(0))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujgestosc()
if inp == 18:
    ahfioufga= wszst(float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jakie g? ')),
    float(0),
    float(0),
    float(0),
    float(0),
    float(input('jaka objętość? ')),
    float(input('jaka gęstość cieczy? ')))
    lista = [ahfioufga]
    for obj in lista:
        obj.kalkulujwypornosc()