class wszst:


    s = float(0)
    v = float(0)
    t = float(0)
    v0 = float(0)
    vk = float(0)
    s0 = float(0)
    t0 = float(0)
    sk = float(0)
    tk = float(0)
    a = float(0)
    vsr = float(0)
    x0 = float(0)
    xt = float(0)
    asr = float(0)
    deltav = float(0)
    deltat = float(0)
    adodelty = float(0)
    bdodelty = float(0)
    cdodelty = float(0)
    fn = float(0)
    fs = float(0)
    m = float(0)
    g = float(0)
    p = float(0)
    cd = float(0)
    area = float(0)
    c = float(299792458)
    objetosc = float(0)
    dc = float(0)


